# Generated by Django 3.1.7 on 2021-10-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
