# Generated by Django 3.1.7 on 2021-10-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='message',
        ),
    ]
